robot:
  name: "xarm6"
  dof: 6
  
  joint_limits:
    joint1: [-6.28319, 6.28319]    # ±2π
    joint2: [-2.059, 2.0944]       # From URDF
    joint3: [-3.927, 0.19198]      # From URDF
    joint4: [-6.28319, 6.28319]    # ±2π
    joint5: [-1.69297, 3.14159]    # From URDF
    joint6: [-6.28319, 6.28319]    # ±2π

  # DH parameters need verification from kinematics config
  dh_params:
    joint1: [0, -1.5708, 0.267, 0]
    joint2: [0.0535, 0, 0, -0.5]
    joint3: [0.2845, -1.5708, 0, -0.5]
    joint4: [0, 1.5708, 0.3425, 0]
    joint5: [0, -1.5708, 0, -0.95]
    joint6: [0, 0, 0.097, 0]

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  mlp_layers: [64, 64, 64]
